name: weparty
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  parse_server_sdk_flutter: ^7.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/banner/
    - assets/images/categorias/
    - assets/images/logo/
    - assets/images/lojas/
    - assets/images/onboarding/
    - assets/images/perfil/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
